#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NetExam.Resource", IsApplication=true)]

namespace NetExam
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_right = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int attendeelist_background_color = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int attendeelist_lblEventName_txtcolor = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int attendeelist_lblHeader_txtcolor = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int attendeelistview_background_color = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int attendeelistview_txtcolor = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int attendeestatus_background_color = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int attendeestatus_lblHeader_color = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int eventdetail_background_color = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int eventdetail_lblHeader_color = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int eventdetail_txtcolor = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int eventlist_background_color = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int eventlist_lblHeader_color = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int eventlist_txtcolor = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int eventlistview_txtcolor = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int helpme_txtcolor = 2131034129;
			
			// aapt resource value: 0x7f050002
			public const int loginhelp_button_text_color = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int text_color = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int text_hint_color = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060012
			public const int login_bottom_helpme_margintop = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int login_bottom_helpme_textsize = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int login_bottom_helpme_width = 2131099667;
			
			// aapt resource value: 0x7f06000c
			public const int login_bottom_layout_margintop = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int login_bottom_layout_paddingend = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int login_bottom_layout_paddingstart = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int login_content_layout_margintop = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int login_content_textbox_drawablepadding = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int login_content_textbox_height = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int login_content_textbox_paddingbottom = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int login_content_textbox_paddingend = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int login_content_textbox_paddingstart = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int login_content_textbox_paddingtop = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int login_content_textbox_width = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int login_header_image_height = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int login_header_image_margintop = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int login_header_image_paddingtop = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int login_header_image_width = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int login_loginbutton_margintop = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int login_loginbutton_textsize = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int login_loginbutton_width = 2131099663;
			
			// aapt resource value: 0x7f060018
			public const int loginhelp_button_margintop = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int loginhelp_button_text_size = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int loginhelp_button_width = 2131099673;
			
			// aapt resource value: 0x7f060015
			public const int loginhelp_padding = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int loginhelp_text_size = 2131099670;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AppIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrowDark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arrowLight = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int arrowWhite = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int backButton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Border = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int boxDark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int boxGrey = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int boxgreystyle = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int boxLight = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int button1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int button2dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int buttonLight = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int buttonsyle = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int canceleventbuttonstyle = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int createeventbuttonstyle = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int dateICon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int downArrow = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int DrwablePadding = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int durationICon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int edittextstyle = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int eventIcon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int fontbold = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int loginButton = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int logogLarge = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int mainWhitBoxShadow = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Menu = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int passwordCharacter = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int passwordICon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int QRscan = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int sideArrow = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int SideCloseButton = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int sidecreateEventICon = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int sideEvaluationIcon = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int sideHomeicon = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int signoutbutton = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int splashscreenBg = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int studentIcon = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int timeicon = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int topbar = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int topbarLogo = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int topbarShadow = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int usernameicon = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int userNameIocn = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int whitebackgroundroundcorner = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int whitebuttonstyle = 2130837551;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0050
			public const int ScrollViewBody = 2131361872;
			
			// aapt resource value: 0x7f0a0078
			public const int actionBarLogo = 2131361912;
			
			// aapt resource value: 0x7f0a000c
			public const int btnCancel = 2131361804;
			
			// aapt resource value: 0x7f0a0054
			public const int btnCreateAttendee = 2131361876;
			
			// aapt resource value: 0x7f0a0061
			public const int btnCreateEvent = 2131361889;
			
			// aapt resource value: 0x7f0a001f
			public const int btnLaunch = 2131361823;
			
			// aapt resource value: 0x7f0a001b
			public const int btnLogin = 2131361819;
			
			// aapt resource value: 0x7f0a000d
			public const int btnSave = 2131361805;
			
			// aapt resource value: 0x7f0a0049
			public const int btnSignout = 2131361865;
			
			// aapt resource value: 0x7f0a000f
			public const int ddlEventType = 2131361807;
			
			// aapt resource value: 0x7f0a0023
			public const int framelayout_maincontainer = 2131361827;
			
			// aapt resource value: 0x7f0a0000
			public const int getSection = 2131361792;
			
			// aapt resource value: 0x7f0a006f
			public const int getlinearlayout5 = 2131361903;
			
			// aapt resource value: 0x7f0a0016
			public const int imageView1 = 2131361814;
			
			// aapt resource value: 0x7f0a004b
			public const int imgIcon = 2131361867;
			
			// aapt resource value: 0x7f0a003c
			public const int imgIconCreateAttendee = 2131361852;
			
			// aapt resource value: 0x7f0a002e
			public const int imgIconCreateEvent = 2131361838;
			
			// aapt resource value: 0x7f0a0027
			public const int imgIconHome = 2131361831;
			
			// aapt resource value: 0x7f0a0043
			public const int imgIconMyAttendees = 2131361859;
			
			// aapt resource value: 0x7f0a0035
			public const int imgIconMyEvents = 2131361845;
			
			// aapt resource value: 0x7f0a0040
			public const int imgsideArrowCreateAttendee = 2131361856;
			
			// aapt resource value: 0x7f0a0032
			public const int imgsideArrowCreateEvent = 2131361842;
			
			// aapt resource value: 0x7f0a002b
			public const int imgsideArrowHome = 2131361835;
			
			// aapt resource value: 0x7f0a0047
			public const int imgsideArrowMyAttendees = 2131361863;
			
			// aapt resource value: 0x7f0a0039
			public const int imgsideArrowMyEvents = 2131361849;
			
			// aapt resource value: 0x7f0a006d
			public const int lbStartlDate = 2131361901;
			
			// aapt resource value: 0x7f0a0014
			public const int lblAttendee = 2131361812;
			
			// aapt resource value: 0x7f0a000a
			public const int lblComments = 2131361802;
			
			// aapt resource value: 0x7f0a005b
			public const int lblCount = 2131361883;
			
			// aapt resource value: 0x7f0a006a
			public const int lblDate = 2131361898;
			
			// aapt resource value: 0x7f0a005f
			public const int lblDisplay = 2131361887;
			
			// aapt resource value: 0x7f0a0065
			public const int lblEmail = 2131361893;
			
			// aapt resource value: 0x7f0a0072
			public const int lblEndDate = 2131361906;
			
			// aapt resource value: 0x7f0a0012
			public const int lblEndDateTime = 2131361810;
			
			// aapt resource value: 0x7f0a0074
			public const int lblEndTime = 2131361908;
			
			// aapt resource value: 0x7f0a0004
			public const int lblEvent = 2131361796;
			
			// aapt resource value: 0x7f0a0053
			public const int lblEventName = 2131361875;
			
			// aapt resource value: 0x7f0a000e
			public const int lblEventType = 2131361806;
			
			// aapt resource value: 0x7f0a0001
			public const int lblHeader = 2131361793;
			
			// aapt resource value: 0x7f0a001c
			public const int lblLogin = 2131361820;
			
			// aapt resource value: 0x7f0a005d
			public const int lblMnth = 2131361885;
			
			// aapt resource value: 0x7f0a0002
			public const int lblName = 2131361794;
			
			// aapt resource value: 0x7f0a0008
			public const int lblScore = 2131361800;
			
			// aapt resource value: 0x7f0a0010
			public const int lblStartDateTime = 2131361808;
			
			// aapt resource value: 0x7f0a0070
			public const int lblStartTime = 2131361904;
			
			// aapt resource value: 0x7f0a0006
			public const int lblStatus = 2131361798;
			
			// aapt resource value: 0x7f0a004d
			public const int lblTxt = 2131361869;
			
			// aapt resource value: 0x7f0a003e
			public const int lblTxtCreateAttendee = 2131361854;
			
			// aapt resource value: 0x7f0a0030
			public const int lblTxtCreateEvent = 2131361840;
			
			// aapt resource value: 0x7f0a0029
			public const int lblTxtHome = 2131361833;
			
			// aapt resource value: 0x7f0a0045
			public const int lblTxtMyAttendees = 2131361861;
			
			// aapt resource value: 0x7f0a0037
			public const int lblTxtMyEvents = 2131361847;
			
			// aapt resource value: 0x7f0a0021
			public const int left_fragment_container = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public const int left_fragment_drawer = 2131361826;
			
			// aapt resource value: 0x7f0a001a
			public const int linearLayout1 = 2131361818;
			
			// aapt resource value: 0x7f0a0017
			public const int linearLayout2 = 2131361815;
			
			// aapt resource value: 0x7f0a001d
			public const int linearLayoutcontent = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int linearLayoutmaincontent = 2131361822;
			
			// aapt resource value: 0x7f0a0062
			public const int linearlayout1 = 2131361890;
			
			// aapt resource value: 0x7f0a0063
			public const int linearlayout2 = 2131361891;
			
			// aapt resource value: 0x7f0a0064
			public const int linearlayout3 = 2131361892;
			
			// aapt resource value: 0x7f0a0068
			public const int linearlayout4 = 2131361896;
			
			// aapt resource value: 0x7f0a0069
			public const int linearlayout5 = 2131361897;
			
			// aapt resource value: 0x7f0a0076
			public const int linearlayout6 = 2131361910;
			
			// aapt resource value: 0x7f0a0077
			public const int linearlayout7 = 2131361911;
			
			// aapt resource value: 0x7f0a0052
			public const int lstAttendees = 2131361874;
			
			// aapt resource value: 0x7f0a0060
			public const int lstEvents = 2131361888;
			
			// aapt resource value: 0x7f0a0020
			public const int myMenuDrawer = 2131361824;
			
			// aapt resource value: 0x7f0a004a
			public const int relativeLayout2 = 2131361866;
			
			// aapt resource value: 0x7f0a004c
			public const int relativeLayout3 = 2131361868;
			
			// aapt resource value: 0x7f0a004e
			public const int relativeLayout4 = 2131361870;
			
			// aapt resource value: 0x7f0a0051
			public const int relativeLayout5 = 2131361873;
			
			// aapt resource value: 0x7f0a0057
			public const int relativeLayoutcentercontent = 2131361879;
			
			// aapt resource value: 0x7f0a0055
			public const int relativeLayoutcontainer = 2131361877;
			
			// aapt resource value: 0x7f0a003a
			public const int relativeLayoutcontainerCreateAttendee = 2131361850;
			
			// aapt resource value: 0x7f0a002c
			public const int relativeLayoutcontainerCreateEvent = 2131361836;
			
			// aapt resource value: 0x7f0a0025
			public const int relativeLayoutcontainerHome = 2131361829;
			
			// aapt resource value: 0x7f0a0041
			public const int relativeLayoutcontainerMyAttendees = 2131361857;
			
			// aapt resource value: 0x7f0a0033
			public const int relativeLayoutcontainerMyEvents = 2131361843;
			
			// aapt resource value: 0x7f0a0048
			public const int relativeLayoutfooter = 2131361864;
			
			// aapt resource value: 0x7f0a004f
			public const int relativeLayoutheader = 2131361871;
			
			// aapt resource value: 0x7f0a0056
			public const int relativeLayoutleftimage = 2131361878;
			
			// aapt resource value: 0x7f0a003b
			public const int relativeLayoutleftimageCreateAttendee = 2131361851;
			
			// aapt resource value: 0x7f0a002d
			public const int relativeLayoutleftimageCreateEvent = 2131361837;
			
			// aapt resource value: 0x7f0a0026
			public const int relativeLayoutleftimageHome = 2131361830;
			
			// aapt resource value: 0x7f0a0042
			public const int relativeLayoutleftimageMyAttendees = 2131361858;
			
			// aapt resource value: 0x7f0a0034
			public const int relativeLayoutleftimageMyEvents = 2131361844;
			
			// aapt resource value: 0x7f0a005a
			public const int relativeLayoutmonth = 2131361882;
			
			// aapt resource value: 0x7f0a0059
			public const int relativeLayoutmonthcontainer = 2131361881;
			
			// aapt resource value: 0x7f0a005c
			public const int relativeLayoutmonthname = 2131361884;
			
			// aapt resource value: 0x7f0a0058
			public const int relativeLayoutrightcontent = 2131361880;
			
			// aapt resource value: 0x7f0a005e
			public const int relativeLayoutrightimage = 2131361886;
			
			// aapt resource value: 0x7f0a003f
			public const int relativeLayoutrightimageCreateAttendee = 2131361855;
			
			// aapt resource value: 0x7f0a0031
			public const int relativeLayoutrightimageCreateEvent = 2131361841;
			
			// aapt resource value: 0x7f0a002a
			public const int relativeLayoutrightimageHome = 2131361834;
			
			// aapt resource value: 0x7f0a0046
			public const int relativeLayoutrightimageMyAttendees = 2131361862;
			
			// aapt resource value: 0x7f0a0038
			public const int relativeLayoutrightimageMyEvents = 2131361848;
			
			// aapt resource value: 0x7f0a003d
			public const int relativeLayouttextCreateAttendee = 2131361853;
			
			// aapt resource value: 0x7f0a002f
			public const int relativeLayouttextCreateEvent = 2131361839;
			
			// aapt resource value: 0x7f0a0028
			public const int relativeLayouttextHome = 2131361832;
			
			// aapt resource value: 0x7f0a0044
			public const int relativeLayouttextMyAttendees = 2131361860;
			
			// aapt resource value: 0x7f0a0036
			public const int relativeLayouttextMyEvents = 2131361846;
			
			// aapt resource value: 0x7f0a0024
			public const int relativelayoutdrawer = 2131361828;
			
			// aapt resource value: 0x7f0a0015
			public const int txtAttendee = 2131361813;
			
			// aapt resource value: 0x7f0a000b
			public const int txtCommnets = 2131361803;
			
			// aapt resource value: 0x7f0a006b
			public const int txtDate = 2131361899;
			
			// aapt resource value: 0x7f0a0066
			public const int txtEmail = 2131361894;
			
			// aapt resource value: 0x7f0a0073
			public const int txtEndDate = 2131361907;
			
			// aapt resource value: 0x7f0a0013
			public const int txtEndDateTime = 2131361811;
			
			// aapt resource value: 0x7f0a0075
			public const int txtEndTime = 2131361909;
			
			// aapt resource value: 0x7f0a0005
			public const int txtEvent = 2131361797;
			
			// aapt resource value: 0x7f0a0067
			public const int txtLblStatus = 2131361895;
			
			// aapt resource value: 0x7f0a006c
			public const int txtLblType = 2131361900;
			
			// aapt resource value: 0x7f0a0003
			public const int txtName = 2131361795;
			
			// aapt resource value: 0x7f0a0019
			public const int txtPassword = 2131361817;
			
			// aapt resource value: 0x7f0a0009
			public const int txtScore = 2131361801;
			
			// aapt resource value: 0x7f0a006e
			public const int txtStartDate = 2131361902;
			
			// aapt resource value: 0x7f0a0011
			public const int txtStartDateTime = 2131361809;
			
			// aapt resource value: 0x7f0a0007
			public const int txtStatus = 2131361799;
			
			// aapt resource value: 0x7f0a0071
			public const int txtTime = 2131361905;
			
			// aapt resource value: 0x7f0a0018
			public const int txtUsername = 2131361816;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070002
			public const int lines = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int loginhelp_layout_weight = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int max_lines = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int pass_maxlength = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int user_maxlength = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateAttendee = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateEvent = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LoginHelp = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int menu_drawer = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int myattendee_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MyAttendees = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int myevent_item = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MyEvents = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ViewAttendee = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ViewEvent = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080003
			public const int Close_Drawer = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int Open_Drawer = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int hello = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int login_bottom_helpme_text = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int login_bottom_login_text = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int login_content_password_hint = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int login_content_username_hint = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int loginhelp_button_text = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int loginhelp_text = 2131230728;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090001
			public const int MyTheme = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int Theme_Splash = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
